// Isolated data: no production database, charge, or outgoing notification.
process.env.NODE_ENV = 'test'; process.env.PAYMENT_MODE = 'mock'; process.env.PAYMENT_SIGNING_SECRET = 'fixture-only-company-payment-secret';
const assert = require('node:assert/strict');
const mongoose = require('mongoose'); mongoose.set('bufferCommands', false);
const Company = require('../src/modules/members/company.model');
const Member = require('../src/modules/members/memberdetails.model');
const Order = require('../src/modules/payment/paymentorder.model');
const publishing = require('../src/modules/members/companyPublishing');
const uid = new mongoose.Types.ObjectId().toString();
const member = { _id: uid, email: 'fixture@example.test', membershipStatus: 'active', membershipType: 'annual', membershipExpiresAt: new Date(Date.now() + 86400000 * 200), isActive: true, paymentId: 'original-payment', paymentAmount: 5000 };
const first = { _id: new mongoose.Types.ObjectId().toString(), userId: uid, isActive: true, status: 'pending', createdAt: new Date('2026-01-01') };
const second = { _id: new mongoose.Types.ObjectId().toString(), userId: uid, businessName: 'Second company', isActive: false, createdAt: new Date('2026-02-01') };
let companies = [first, second], orders = [];
const query = value => ({ select() { return this; }, sort() { return this; }, lean: async () => structuredClone(value), catch(fn) { return Promise.resolve(value).catch(fn); }, then(resolve, reject) { return Promise.resolve(value).then(resolve, reject); } });
Member.findById = id => query(String(id) === uid ? member : null);
Member.findByIdAndUpdate = () => { throw Error('Company payments must never rewrite membership'); };
Company.find = () => query(companies);
Company.findOne = filter => query(companies.find(c => String(c._id) === String(filter._id) && c.userId === String(filter.userId)));
Company.updateOne = Company.findOneAndUpdate = async (filter, patch) => { const c = companies.find(c => String(c._id) === String(filter._id)); Object.assign(c, patch.$set || patch); return c; };
Order.find = () => query(orders.filter(o => o.status === 'paid'));
Order.findOne = filter => query(filter.orderId ? orders.find(o => o.orderId === filter.orderId) : { planId: 'basic' });
Order.findById = id => query(orders.find(o => String(o._id) === String(id)));
Order.create = async value => { const o = { ...value, _id: new mongoose.Types.ObjectId(), status: 'created' }; orders.push(o); return o; };
Order.findOneAndUpdate = async (filter, patch) => { const o = orders.find(o => String(o._id) === String(filter._id) && o.status === filter.status && (!filter.settlementToken || filter.settlementToken === o.settlementToken)); if (!o) return null; Object.assign(o, patch.$set || patch); for (const key of Object.keys(patch.$unset || {})) delete o[key]; return o; };
Order.updateOne = Order.findOneAndUpdate;
require('../src/modules/members/membershipplan.service').getPlanForPayment = async key => ({ id: key, name: 'Starter', amount: 5000, membershipType: 'annual', audience: 'business' });
async function main() {
    let state = publishing.publicationState(member, companies, []);
    assert.deepEqual([...state.published], [first._id]);
    assert.equal(publishing.decorate(first, state).status, 'active', 'stale pending is not a review');
    assert.equal(publishing.decorate(second, state).publication.paymentRequired, true);
    await assert.rejects(publishing.assertCanPublish(uid, second._id), /one company/);
    assert.equal((await publishing.quote(uid, second._id)).amount, 5000);
    await assert.rejects(publishing.quote(new mongoose.Types.ObjectId().toString(), second._id), /not found/);
    const racing = companies.map(c => ({ ...c, isActive: true }));
    assert.equal(publishing.publicationState(member, racing, []).published.size, 1);
    assert.equal(publishing.publicationState({ ...member, membershipTier: 'platinum', membershipType: 'lifetime' }, racing, []).published.size, 2);
    assert.equal(publishing.publicationState({ ...member, isActive: false }, racing, []).published.size, 0);
    assert.equal(publishing.publicationState({ ...member, membershipExpiresAt: new Date('2000-01-01') }, racing, []).published.size, 0);
    const orderService = require('../src/modules/payment/paymentOrder.service');
    const { receipt } = await orderService.createOrder({ userId: uid }, { companyId: second._id, planId: 'student' });
    assert.equal(receipt.amount, 5000, 'client cannot choose cheaper additional-company fee');
    const auth = await orderService.authorizeMock({ userId: uid }, { orderId: receipt.orderId });
    await assert.rejects(orderService.completePayment({ userId: uid }, { orderId: receipt.orderId, gatewayPaymentId: auth.gatewayPaymentId, signature: 'wrong' }), /signature/);
    await orderService.completePayment({ userId: uid }, { ...auth });
    assert.equal((await publishing.ownerContext(uid)).published.size, 2);
    assert.equal(member.paymentAmount, 5000); assert.equal(member.paymentId, 'original-payment');
    await assert.rejects(orderService.completePayment({ userId: uid }, { ...auth }), /already/);
    // Real gateway settlement shares the same immutable membership behavior.
    const paid = orders[0]; orders = [{ ...paid, _id: new mongoose.Types.ObjectId(), orderId: 'ord_fixture_gateway', status: 'created', provider: 'instamojo' }];
    const payment = require('../src/modules/payment/payment.service');
    await payment.settleMembershipOrder(orders[0], 'MOJO-fixture');
    const paidAt = orders[0].paidAt;
    await payment.settleMembershipOrder(orders[0], 'MOJO-fixture');
    assert.equal(orders[0].paidAt, paidAt, 'webhook replay never adds time');
    assert.equal((await publishing.ownerContext(uid)).published.size, 2);
    const expired = [{ ...orders[0], paidAt: new Date('2000-01-01') }];
    assert.equal(publishing.publicationState(member, companies, expired).published.size, 1);
    const schema = new Order({ ...orders[0], currency: 'INR', expiresAt: new Date() });
    assert.equal(schema.validateSync(), undefined);
    console.log('PASS: Lifetime multi-company, one included company, payment pricing, ownership, signed payment, replay, expiry, and unchanged personal membership.');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
