const assert = require('node:assert/strict');
const send = require('../src/modules/auth/oauthReturnPage');
let html, headers, redirect;
const res = { set(value) { headers = value; return this; }, type() { return this; }, send(value) { html = value; }, redirect(value) { redirect = value; } };
send({ headers: { 'user-agent': 'Android Chrome' } }, res, 'activ://auth/social?code=fixture&provider=facebook');
assert.match(html, /intent:\/\/auth\/social\?code=fixture&amp;provider=facebook#Intent;scheme=activ;package=in.activ.membership;end/);
assert.match(html, />Open ACTIV<\/a>/);
assert.equal(headers['Cache-Control'], 'no-store');
assert.equal(headers['Referrer-Policy'], 'no-referrer');
assert.match(headers['Content-Security-Policy'], /frame-ancestors 'none'/);
send({ headers: {} }, res, 'https://activ.org.in/auth/social#code=fixture');
assert.equal(redirect, 'https://activ.org.in/auth/social#code=fixture');
send({ headers: {} }, res, 'activ://auth/social?error=expired&provider=facebook');
assert.match(html, /href="activ:\/\/auth\/social\?error=expired&amp;provider=facebook"/);
console.log('PASS: Facebook/browser return page, Android explicit intent, website redirects, and no caching.');
const jwt = require('jsonwebtoken');
const config = require('../src/config');
const oauth = require('../src/modules/auth/oauth.service');
const expired = jwt.sign({ t: 'oauth-state', c: 'app', p: 'facebook', n: 'fixture' }, config.jwt.secret, { expiresIn: -1 });
assert.equal(oauth.clientFromState(expired), 'app', 'expired mobile flows still show their error in the app');
assert.equal(oauth.clientFromState(jwt.sign({ t: 'oauth-state', c: 'app' }, 'wrong-signature')), '');
process.exit(0);
