const assert = require('node:assert/strict');
const mongoose = require('mongoose');
mongoose.set('bufferCommands', false);
const Member = require('../src/modules/members/memberdetails.model');
const Application = require('../src/modules/applications/application.model');
const Order = require('../src/modules/payment/paymentorder.model');
const requests = require('../src/modules/members/platinumrequest.model');
const notices = [], orders = [], members = [], apps = [];
const query = value => ({ select() { return this; }, sort() { return this; }, limit() { return this; }, lean: async () => structuredClone(value) });
Member.findOne = filter => { const m = members.find(m => filter.email === m.email || filter.phoneNumber?.test?.(m.phoneNumber)); return query(m ? { ...m, _id: String(m._id) } : null); };
Member.findById = async id => { const m = members.find(m => String(m._id) === String(id)); return m ? new Member(m) : null; };
Member.findOneAndUpdate = async (filter, patch) => {
    const m = members.find(m => String(m._id) === String(filter._id));
    if (!m || m.membershipTier === 'platinum' || +m.updatedAt !== +filter.updatedAt) return null;
    Object.assign(m, patch.$set, { updatedAt: new Date(+m.updatedAt + 1) }); return new Member(m);
};
Application.find = filter => query(filter.userId ? apps.filter(a => filter.userId.$in.map(String).includes(String(a.userId))) : apps);
Application.distinct = async field => [...new Set(apps.map(a => a[field]))];
Order.create = async data => { const row = { ...data, _id: new mongoose.Types.ObjectId() }; orders.push(row); return row; };
Order.updateOne = async (filter, patch) => Object.assign(orders.find(o => String(o._id) === String(filter._id)), patch.$set);
requests.updateMany = async () => null;
require('../src/modules/members/membershipplan.service').listAll = async () => [{ key: 'platinum', name: 'Platinum Lifetime', price: 200000, active: true }];
require('../src/modules/members/memberNumber').assignMembershipNumber = async () => 'ACTIV-2026-TEST';
require('../src/modules/members/memberIds').idsFor = async () => ({ applicationRef: '' });
require('../src/modules/notifications/notification.service').dispatchInBackground = (...args) => notices.push(args);
const extrasPath = require.resolve('../src/modules/members/memberExtras.controller');
require.cache[extrasPath] = { id: extrasPath, filename: extrasPath, loaded: true, exports: { recordActivity: async () => null } };
const service = require('../src/modules/members/platinum.service');
const actor = { role: 'super_admin', userId: new mongoose.Types.ObjectId().toString(), email: 'office@example.test' };
const fixture = () => { const m = { _id: new mongoose.Types.ObjectId(), fullName: 'Office Member', email: 'member@example.test', phoneNumber: '9092317264', role: 'member', membershipStatus: 'pending', membershipType: 'none', membershipTier: 'standard', isActive: true, updatedAt: new Date(), createdAt: new Date() }; members.push(m); return m; };
const body = { amount: 200000, paymentMode: 'cash', manualAdmission: true, note: 'Super Admin admitted after receiving cash at the office.' };
async function main() {
    const member = fixture();
    await assert.rejects(service.grant(member._id, body, { role: 'district_admin' }), e => e.statusCode === 403);
    await assert.rejects(service.grant(member._id, { ...body, manualAdmission: false }, actor), /submitted an application/);
    await assert.rejects(service.grant(member._id, { ...body, amount: 0 }, actor), /positive amount/);
    await assert.rejects(service.grant(member._id, { ...body, note: '' }, actor), /submitted an application/);
    const granted = await service.grant(member._id, body, actor);
    assert.equal(granted.membershipTier, 'platinum'); assert.equal(granted.membershipStatus, 'active');
    assert.equal(granted.membershipType, 'lifetime'); assert.equal(member.membershipExpiresAt, null);
    assert.equal(orders[0].amount, 200000); assert.equal(orders[0].provider, 'offline');
    assert.equal(orders[0].manualConfirmation.by, actor.userId);
    assert.match(orders[0].manualConfirmation.note, /office admission/);
    assert.equal(notices[0][0], 'MEMBERSHIP_ACTIVATED');
    assert.equal(notices[0][2].membershipType, 'lifetime');
    assert.equal(apps.length, 0, 'office admission does not invent an approved application');
    await assert.rejects(service.grant(member._id, body, actor), /already a Lifetime/);
    const simultaneous = fixture();
    const results = await Promise.allSettled([service.grant(simultaneous._id, body, actor), service.grant(simultaneous._id, body, actor)]);
    assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
    assert.equal(orders.filter(o => String(o.memberId) === String(simultaneous._id) && o.status === 'paid').length, 1);
    const business = fixture();
    Object.assign(business, { email: 'business@example.test', phoneNumber: '9000000000', memberType: 'business', membershipStatus: 'active', membershipType: 'annual' });
    const originalId = String(business._id);
    const Auth = require('../src/modules/auth/auth.model');
    const denyCredentialWrite = async () => { throw new Error('An upgrade must never change login credentials'); };
    Auth.updateOne = denyCredentialWrite; Auth.findOneAndUpdate = denyCredentialWrite; Auth.create = denyCredentialWrite;
    await service.grant(business._id, { amount: 200000, paymentMode: 'cash', note: 'Existing business member upgrade' }, actor);
    assert.equal(String(business._id), originalId);
    assert.equal(business.email, 'business@example.test'); assert.equal(business.phoneNumber, '9000000000');
    assert.equal(business.memberType, 'business'); assert.equal(business.membershipTier, 'platinum');
    assert.equal(business.membershipType, 'lifetime'); assert.equal(business.membershipExpiresAt, null);
    assert.equal(String(orders.at(-1).memberId), originalId);
    await assert.rejects(service.createAccount({ email: business.email, phoneNumber: business.phoneNumber, password: 'unchanged-secret' }, actor), /already exists/);
    const reused = await service.createAccount({ email: business.email, phoneNumber: business.phoneNumber }, actor);
    assert.equal(reused.id, originalId); assert.equal(reused.existingAccount, true);
    const phoneOnly = await service.createAccount({ phoneNumber: business.phoneNumber }, actor);
    assert.equal(phoneOnly.id, originalId);
    member.phoneNumber = business.phoneNumber;
    const exactEmail = await service.createAccount({ email: business.email, phoneNumber: business.phoneNumber }, actor);
    assert.equal(exactEmail.id, originalId, 'the exact email wins when another older registration shares a mobile number');
    const registration = require('../src/modules/auth/auth.service');
    registration.register = async payload => { assert.equal(payload.password, 'test-password'); return { memberDetails: fixture(), token: 'must-not-leak' }; };
    const account = await service.createAccount({ email: 'new-office@example.test', password: 'test-password' }, actor);
    assert.equal(account.password, undefined); assert.equal(account.token, undefined); assert.equal(account.canAdmitManually, true);
    await assert.rejects(service.createAccount({}, { role: 'member' }), e => e.statusCode === 403);
    for (let i = 0; i < 22; i++) apps.push({ state: 'Tamil Nadu', district: i < 3 ? 'Ariyalur' : 'Chennai', block: 'Block', status: 'Pending' });
    const hub = require('../src/modules/admin/superadmin.service'); hub.allAdminRows = async () => [];
    const directory = await hub.computeDirectory({ level: 'state' }, { role: 'super_admin' });
    const tamil = directory.regions.find(r => r.name === 'Tamil Nadu');
    assert.equal(tamil.applications, 22); assert.equal(tamil.state, 'Tamil Nadu'); assert.equal(tamil.district, ''); assert.equal(tamil.block, '');
    console.log('Platinum office admission: account response privacy, Super Admin permissions, cash receipt, lifetime access, notifications, concurrency and state-region count regression passed.');
}
main().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
