const mongoose = require('mongoose');

/**
 * A booking for seats at an event — THE record of who is coming.
 *
 * ------------------------------------- the one record, and why it had to be
 *
 * `EventRegistration` came first and is a different shape: one row is one
 * MEMBER's own seat, keyed by `userId`, with a unique index on
 * `(eventId, userId)`. It cannot express what the association asked for —
 *
 *   - a GUEST has no `userId` at all, and `userId` there is `required`;
 *   - one booking covers SEVERAL PARTICIPANTS, each with their own name, email
 *     and mobile, and the money is charged once for all of them;
 *   - the same person books twice, for more colleagues, and the unique index
 *     would refuse the second booking.
 *
 * For a while both existed and BOTH were live, and that was the mistake. A
 * member booking through the new flow wrote here, while their event page read
 * `myRegistration` out of the old collection — so the member booked, paid, and
 * the app showed no trace of it and offered them "Book Now" again. The
 * organiser had two attendee lists for one room, and only the seat count added
 * them up.
 *
 * This is now the single record. `EventRegistration` is read-only legacy: seats
 * already taken there still count and still show, and nothing new is written to
 * it. It held zero rows when the change was made, so nothing was migrated and
 * nothing was lost.
 *
 * ---------------------------------------------------- everything is a COPY
 *
 * The event's title, date, venue and PRICE are written onto the booking at the
 * moment it is taken, not joined at read time. The same reasoning the member
 * registration schema gives for copying a member's phone number, and a stronger
 * one for the price: an organiser who raises the fee next week has not changed
 * what this person agreed to pay, and a receipt that recalculates itself is not
 * a receipt. `unitAmount * noOfPersons === totalAmount` is true forever on the
 * stored row, whatever the event says later.
 */

/**
 * One person attending, as the booker typed them.
 *
 * `_id: false` — a participant is a line on a booking, not an entity anything
 * else points at. Giving each one an ObjectId would invite code that looks a
 * participant up by it, and the row it would find can be rewritten wholesale by
 * the booker editing their own booking.
 */
const participantSchema = new mongoose.Schema({
    name: { type: String, trim: true, default: '' },
    email: { type: String, trim: true, lowercase: true, default: '' },
    phone: { type: String, trim: true, default: '' }
}, { _id: false });

const eventBookingSchema = new mongoose.Schema({
    eventId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Event',
        required: true,
        index: true
    },

    /**
     * The reference a human uses — on the receipt, in an email, over the phone.
     *
     * Generated by the server and unique, because it is the ONLY handle a guest
     * has on their own booking. A guest has no account to sign into and no list
     * to open: if they lose this string they cannot reach their booking again,
     * which is why it is also what `GET /event-bookings/:ref` takes.
     *
     * Not the ObjectId. Printing a 24-character hex id on a confirmation page
     * reads as an internal error leaking onto a receipt, and it is a poor thing
     * to read down a telephone.
     */
    bookingRef: {
        type: String,
        trim: true,
        uppercase: true,
        required: true,
        unique: true,
        index: true
    },

    // ------------------------------------------------------------ who booked

    /**
     * The person who made the booking and who the receipt belongs to.
     *
     * Kept separate from `participants` even when they are the same person. The
     * booker is who to contact about the money; a participant is who is coming.
     * The client's own screens print them as two sections for that reason, and
     * a booking where the booker is not attending is an ordinary case — an
     * office manager booking two colleagues onto a conclave.
     */
    bookedBy: {
        name: { type: String, trim: true, default: '' },
        email: { type: String, trim: true, lowercase: true, default: '' },
        phone: { type: String, trim: true, default: '' }
    },

    /**
     * `MemberDetails._id` as a string when the booking was made signed in, and
     * an empty string when it was made as a guest.
     *
     * A string rather than an ObjectId ref, matching `EventRegistration.userId`
     * and every other member-owned collection — the token carries it as a
     * string and every comparison in this codebase is `String(a) === String(b)`.
     *
     * Empty rather than null: `''` is a value the guest path writes on purpose,
     * and a sparse index on it behaves predictably. It is NOT unique — the same
     * member may book more than once.
     */
    userId: { type: String, trim: true, default: '', index: true },

    /**
     * Whether this came through the guest checkout.
     *
     * Derivable from `userId` being empty, and stored anyway, because the two
     * answer different questions over time. A guest who registers an account
     * later may have their bookings linked to it; the booking would then have a
     * `userId` and still be, historically, a guest checkout. The admin list
     * shows this column and it must not silently rewrite itself.
     */
    isGuest: { type: Boolean, default: true, index: true },

    // ------------------------------------------------------------ what, and how much

    /**
     * Seats on this booking. At least one — a booking for nobody is not a
     * booking, and `totalAmount` would be zero on a paid event.
     */
    noOfPersons: { type: Number, min: 1, default: 1 },

    /** Everyone attending. Length is reconciled with `noOfPersons` on write. */
    participants: { type: [participantSchema], default: [] },

    /**
     * RUPEES, not paise — matching `Event.registrationFee`, which is what this
     * is copied from.
     *
     * The membership plans store `amountPaise` and these do not, and that
     * difference is real rather than an oversight: the event fee is typed by an
     * organiser in rupees and never divided. Reading `amountPaise` off a
     * booking returns undefined and prints an empty amount on a receipt with
     * nothing reporting an error, so the names are deliberately not shared.
     */
    unitAmount: { type: Number, min: 0, default: 0 },

    /**
     * `unitAmount * noOfPersons`, computed on the SERVER and stored.
     *
     * Stored rather than computed at read time so the receipt, the admin list
     * and the payment all read one number that cannot disagree. Computed on the
     * server rather than accepted from the client for the obvious reason: a
     * total sent from a browser is a price chosen by the buyer.
     */
    totalAmount: { type: Number, min: 0, default: 0 },

    /**
     * Whether `unitAmount` is the event's MEMBER rate rather than its common
     * price — recorded, not recomputed.
     *
     * An event carries two prices (see `eventPricing.js`), and which one a
     * booking was taken at is a fact about that afternoon: the booker's
     * membership was active then. Six months later it may have lapsed, and a
     * receipt that re-derived the rate from the member's status TODAY would
     * reprint last spring's ₹600 booking as a ₹1,000 one and disagree with the
     * money that actually moved.
     *
     * `false` on every row written before this existed, which is correct for
     * all of them: the member rate did not exist, so nothing was taken at it.
     */
    memberRateApplied: { type: Boolean, default: false },

    /**
     * The common price at the moment of booking, kept beside `unitAmount`.
     *
     * Only interesting when the member rate was applied, and then it is the
     * whole story — "₹600, saving ₹400" needs both numbers and neither can be
     * fetched from the event later without re-asking a question whose answer
     * has since changed.
     */
    listAmount: { type: Number, min: 0, default: 0 },

    // ------------------------------------------------------------ the event, as it was

    /**
     * The event's own details at the moment of booking.
     *
     * So a confirmation page, an emailed receipt and the organiser's list all
     * render from the booking alone. An event that is later renamed, moved or
     * cancelled does not rewrite what somebody was sold.
     */
    eventTitle: { type: String, trim: true, default: '' },
    eventStartAt: { type: Date, default: null },
    eventVenue: { type: String, trim: true, default: '' },
    eventMapUrl: { type: String, trim: true, default: '' },

    // ------------------------------------------------------------ money

    payment: {
        /**
         * Three values, three different facts — the same vocabulary
         * `EventRegistration.payment.status` uses, so one reader can understand
         * both collections.
         *
         *   not_required  a free event. The booking is confirmed on the spot.
         *   pending       money is owed. The seats are HELD but do not count
         *                 against capacity — an abandoned checkout must not keep
         *                 a paying attendee out.
         *   paid          settled. The seats are confirmed.
         */
        status: {
            type: String,
            enum: ['not_required', 'pending', 'paid', 'failed'],
            default: 'pending',
            index: true
        },

        /**
         * How it was paid, as the organiser's list prints it.
         *
         * Empty until it settles — an unpaid booking has no payment mode, and
         * defaulting it to 'online' would put a mode against money nobody has
         * taken. The client's reference screen shows exactly this: a blank
         * Payment Mode cell beside a blank Payment Status on the rows that were
         * never completed.
         */
        mode: {
            type: String,
            enum: ['', 'online', 'offline', 'cash', 'upi', 'bank_transfer'],
            default: ''
        },

        /** This server's own order reference, issued when the booking is made. */
        reference: { type: String, trim: true, default: '' },
        /** What the gateway called it. Empty until the gateway answers. */
        gatewayPaymentId: { type: String, trim: true, default: '' },
        paidAt: { type: Date, default: null },

        /**
         * Recorded by an administrator rather than taken through the gateway.
         *
         * An organiser takes cash at the door and marks the booking paid. The
         * money is real and the booking should read as paid; who said so is a
         * separate fact, and one worth keeping when the two sets of numbers are
         * reconciled afterwards.
         */
        recordedBy: { type: String, trim: true, default: '' }
    },

    /**
     * `cancelled` rather than deleting the row — the same rule as a member's
     * seat. A cancelled booking stays visible to the organiser, and cancelling
     * frees the seats because only `active` bookings are counted.
     */
    status: {
        type: String,
        enum: ['active', 'waitlist', 'expired', 'cancelled'],
        default: 'active',
        index: true
    },

    cancelledAt: { type: Date, default: null },
    note: { type: String, trim: true, default: '' },

    /**
     * When an unpaid booking stops holding its seats.
     *
     * =====================================================================
     * A PENDING BOOKING HOLDS ITS SEATS, FOR THIRTY MINUTES
     * =====================================================================
     *
     * It used to hold nothing: pending rows were simply excluded from the seat
     * count, so on the last seat of an event two people could both reach the
     * payment step and the second one paid for a seat that no longer existed.
     * Refunding that is worse than refusing it.
     *
     * The other extreme is an indefinite hold, where three abandoned checkouts
     * show a twenty-seat event as full. Thirty minutes is the window the
     * membership orders already use (`ORDER_TTL_MINUTES`), and using the same
     * number means a deployment has one answer to "how long does a checkout
     * live" rather than two.
     *
     * `null` on anything that is not a pending payment — a confirmed booking
     * does not expire, and neither does a waitlist entry.
     */
    expiresAt: { type: Date, default: null },

    /**
     * Which reminders have gone out, as the hours-before offsets they were
     * sent for (`Event.reminderOffsetsHours`). `sendDueReminders` claims an
     * offset by adding it here, so a reminder is sent once per booking even
     * with several server instances running the timer.
     */
    remindersSent: { type: [Number], default: [] },

    /**
     * The secret that lets a GUEST change their own booking.
     *
     * A member is identified by `userId` and needs none of this. A guest has no
     * account, so something has to stand in — and it must not be `bookingRef`,
     * which is printed on the confirmation page, read down the telephone and
     * quoted at the door. A reference is a ticket: fine for "show me this
     * booking", not for "rewrite it".
     *
     * Issued once, returned once (at booking time), and carried only in the
     * manage link inside the confirmation email. Never in a list response —
     * `toBooking` does not include it, so the organiser's screen cannot leak
     * every guest's edit rights in one JSON payload.
     */
    manageToken: { type: String, trim: true, default: '', select: false },

    /**
     * What the booker's browser was. Not analytics — a public, unauthenticated
     * endpoint that writes rows needs something to look at when it is abused,
     * and an IP with no user agent beside it identifies very little.
     */
    source: { type: String, trim: true, default: 'web' }
}, {
    collection: 'event_bookings',
    timestamps: true
});

/** The organiser's list: this event's bookings, newest first. */
eventBookingSchema.index({ eventId: 1, createdAt: -1 });

/** Seat counting, which filters on all three of these together. */
eventBookingSchema.index({ eventId: 1, status: 1, 'payment.status': 1 });

/**
 * "Has this member booked this event?" — asked for every event in a list.
 *
 * The member's events page resolves it for a whole page of events at once, so
 * without this it is a collection scan per page load on the one screen members
 * open most.
 */
eventBookingSchema.index({ userId: 1, eventId: 1, status: 1 });

/** Sweeping lapsed holds: the expiry sweep matches exactly these three. */
eventBookingSchema.index({ status: 1, 'payment.status': 1, expiresAt: 1 });

/**
 * "Find my bookings" once a guest signs up with the address they booked under.
 * Not unique, deliberately — one address books many events, and many times.
 */
eventBookingSchema.index({ 'bookedBy.email': 1, createdAt: -1 });

module.exports = mongoose.model('EventBooking', eventBookingSchema);
