const mongoose = require('mongoose');

/**
 * A member's seat at an event.
 *
 * A separate collection rather than an array of attendee ids on the event: an
 * event with a few thousand registrations would otherwise be a few thousand
 * subdocuments loaded on every read of the event list, and cancelling a seat
 * would be a write to a document every other member is reading.
 *
 * The member's name, email and phone are COPIED here rather than joined at read
 * time. That is deliberate denormalisation: an attendee list is a record of who
 * signed up and how to reach them on the day, and a member who later changes
 * their phone number has not changed the number they gave the organiser. It
 * also means the list still renders for a member whose record has since been
 * deleted.
 */
const eventRegistrationSchema = new mongoose.Schema({
    eventId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Event',
        required: true,
        index: true
    },
    /**
     * `MemberDetails._id` as a string.
     *
     * A string and not an ObjectId ref, matching `Company.userId` and the rest
     * of the member-owned collections — the token carries it as a string and
     * every comparison in this codebase is `String(a) === String(b)`. Declaring
     * it as an ObjectId here would mean one collection casting where the others
     * do not, and a lookup that silently matches nothing when it fails to cast.
     */
    userId: {
        type: String,
        required: true,
        index: true
    },

    memberName: { type: String, trim: true, default: '' },
    email: { type: String, trim: true, lowercase: true, default: '' },
    phone: { type: String, trim: true, default: '' },
    organization: { type: String, trim: true, default: '' },

    /** Where the member was when they registered — for the organiser's list. */
    state: { type: String, trim: true, default: '' },
    district: { type: String, trim: true, default: '' },
    block: { type: String, trim: true, default: '' },

    /**
     * `cancelled` rather than deleting the row.
     *
     * A cancelled seat has to stay visible to the organiser, and re-registering
     * has to reuse the same row — the unique index below means an insert would
     * fail on the second attempt anyway. Cancelling frees the seat because the
     * capacity count only counts `registered`.
     */
    status: {
        type: String,
        enum: ['registered', 'waitlist', 'cancelled'],
        default: 'registered',
        index: true
    },

    note: { type: String, trim: true, default: '' },

    /**
     * The answers to this event's own registration form (EVT-004).
     *
     * `label` is stored ALONGSIDE the value, not looked up from the event when
     * the attendee list is read. The same denormalisation argument as the name
     * and phone above, and a stronger one: the event's form is editable after
     * people have registered, so a label read at render time would relabel
     * answers somebody already gave — and a field the organiser later deleted
     * would leave its answers with no heading at all, silently dropping a
     * column from the attendee list.
     *
     * Values are stored as strings, including for `number` and `checkbox`. An
     * attendee list is a document, not a dataset: it is read, printed and
     * exported, and a mixed-type column formats differently in every one of
     * those. The field's declared `type` on the event says how it was captured.
     */
    responses: {
        type: [new mongoose.Schema({
            key: { type: String, trim: true, default: '' },
            label: { type: String, trim: true, default: '' },
            value: { type: String, trim: true, default: '' }
        }, { _id: false })],
        default: []
    },

    registeredAt: { type: Date, default: Date.now },
    cancelledAt: { type: Date, default: null },

    /**
     * What this seat cost and whether it has been paid for (EVT-002).
     *
     * A nested object rather than four loose fields, because they are only ever
     * true together: an amount with no status is a number nobody can act on.
     *
     * `status` has three values and each is a different fact:
     *
     *   not_required  the event is free. The seat is confirmed on the spot.
     *   pending       a fee is owed. The seat is HELD but does not count
     *                 against capacity — see `countRegistrations`. An abandoned
     *                 checkout must not keep a paying member out.
     *   paid          settled. The seat is confirmed.
     *
     * `amount` is COPIED from the event at the moment the seat is taken rather
     * than read back from it. An organiser who raises the fee next week has not
     * changed what this member agreed to pay, and a receipt that recalculates
     * itself is not a receipt.
     *
     * `reference` is the transaction id. It is generated by this server for the
     * dummy gateway; when a real gateway is wired in, the id it returns goes in
     * the same field and nothing else has to move.
     */
    payment: {
        status: {
            type: String,
            enum: ['not_required', 'pending', 'paid'],
            default: 'not_required',
            index: true
        },
        amount: { type: Number, min: 0, default: 0 },
        reference: { type: String, trim: true, default: '' },
        method: { type: String, trim: true, default: '' },
        paidAt: { type: Date, default: null }
    }
}, {
    collection: 'event_registrations',
    timestamps: true
});

/**
 * One seat per member per event.
 *
 * Enforced in the database and not only in the service: two taps on a slow
 * connection are two concurrent requests, and both would pass a "have you
 * already registered?" check before either had written. The service catches the
 * resulting E11000 and treats it as "already registered", which is the truth.
 */
eventRegistrationSchema.index({ eventId: 1, userId: 1 }, { unique: true });
eventRegistrationSchema.index({ eventId: 1, status: 1 });

module.exports = mongoose.model('EventRegistration', eventRegistrationSchema);
