const express = require('express');
const mongoose = require('mongoose');
const paymentService = require('./payment.service');
const orderService = require('./paymentOrder.service');
const { listPlans } = require('./membershipPlans');
const membershipPlanService = require('../members/membershipplan.service');
const notificationService = require('../notifications/notification.service');
const ApiResponse = require('../../core/utils/ApiResponse');
const asyncHandler = require('../../core/utils/asyncHandler');
const { verifyToken, optionalAuth, requireRole } = require('../../core/middleware/auth');
const logger = require('../../config/logger');

const router = express.Router();

/**
 * Is the server standing in for the gateway, or is a real one connected?
 *
 * The SAME rule `paymentOrder.service` uses, and it has to stay the same rule:
 * the client picks its checkout from this answer, so a client that thought it
 * was in mock mode while the server was not would call `/mock-authorize` and
 * be refused with nothing to fall back to.
 */
const isMockMode = () =>
    String(process.env.PAYMENT_MODE || 'mock').toLowerCase() === 'mock' &&
    String(process.env.NODE_ENV || '').toLowerCase() !== 'production';

/**
 * GET /api/v1/payment/config
 *
 * WHICH CHECKOUT TO USE, ANSWERED BY THE SERVER.
 *
 * The website had this hardcoded: `payForMembership` always called
 * `/payment/mock-authorize`, so the moment a real gateway was switched on the
 * Pay button would have kept asking for a mock authorisation and getting a
 * 403 — with no message a member could act on.
 *
 * One source of truth instead. `mode` decides which flow the client runs, and
 * `provider` names the gateway so the button can say who it is sending them
 * to. Public shape only: no key, no token, no salt.
 */
router.get('/config', asyncHandler(async(req, res) => {
    const mock = isMockMode();
    res.json(ApiResponse.success({
        mode: mock ? 'mock' : 'gateway',
        provider: mock ? 'mock' : 'instamojo',
        /* So the checkout screen can say "you will be taken to Instamojo"
           rather than presenting a card form this site does not handle. */
        hosted: !mock,
        configured: paymentService.isConfigured()
    }));
}));

/**
 * POST /api/v1/payment/create-request
 * Create a new payment request
 * Requires authentication
 */
/*
 * `optionalAuth`, NOT `verifyToken` — because a SEAT CAN BE BOOKED BY A GUEST.
 *
 * `POST /event-bookings/event/:id` is `optionalAuth` by design: somebody with
 * no ACTIV account can book and pay for a seat. Requiring a token here meant
 * that the moment bookings went through the gateway, every guest booking
 * would 401 on the way to checkout — after they had typed in every
 * participant.
 *
 * A MEMBERSHIP still requires a token, checked below: a membership belongs to
 * an account, so there is nobody to activate without one.
 *
 * Knowing a `bookingRef` is enough to PAY for that booking, and that is not a
 * hole: the reference is generated by the server, and the only thing it buys
 * is settling somebody's bill. Nothing is revealed — the response carries the
 * gateway URL and the amount, both of which the booker has already seen.
 */
router.post('/create-request', optionalAuth, asyncHandler(async(req, res) => {
    const { amount, purpose, membershipType, orderType = 'membership', eventId, bookingRef } = req.body;
    const user = req.user || {};

    if (orderType !== 'event_booking' && !user.userId && !user.email) {
        return res.status(401).json(ApiResponse.error('Please sign in to pay for a membership'));
    }
    
    // Determine the calculated amount based on the order type
    let calculatedAmount = 0;
    let finalPurpose = purpose;
    let planId = membershipType;
    /** Set for an event booking: who the seats were booked by. */
    let bookingContact = null;
    /** The event the booking is for — from the BOOKING, never from the client. */
    let bookingEventId = null;

    if (orderType === 'event_booking') {
        if (!bookingRef) {
            return res.status(400).json(ApiResponse.error('bookingRef is required for event booking'));
        }
        const eventBookingService = require('../events/eventbooking.service');
        const booking = await eventBookingService.getBooking(bookingRef).catch(() => null);
        if (!booking) {
            return res.status(400).json(ApiResponse.error('Invalid booking reference'));
        }
        calculatedAmount = booking.totalAmount;
        finalPurpose = purpose || `ACTIV Event Booking - ${bookingRef}`;
        /* The booking's OWN contact details, which a guest has just typed in
           and a member's profile may not match. They are also what the
           confirmation is sent to, so the gateway receipt and our own email
           reach the same person. */
        bookingContact = booking.bookedBy || {};
        bookingEventId = booking.eventId || null;
    } else {
        const plan = await membershipPlanService.getPlanForPayment(membershipType);
        if (!plan) {
            return res.status(400).json(ApiResponse.error('Invalid membership type'));
        }
        calculatedAmount = Number(plan.amount);
        finalPurpose = purpose || `ACTIV Membership - ${membershipType}`;
    }

    /*
     * THE CLIENT DOES NOT HAVE TO SEND AN AMOUNT, and should not.
     *
     * This required one and rejected anything that did not equal the figure
     * the server had just worked out — which is a safe check but a pointless
     * field: the only value that can ever pass is the one the server already
     * knows. It also made the route unusable from a screen that has a plan id
     * and no price, which is every screen since prices moved into
     * `membershipplan.service`.
     *
     * An amount that IS sent is still checked, so nothing that used to be
     * refused is now accepted. Sending none is simply trusting the server,
     * which is the arrangement the rest of the payment path already has.
     */
    if (amount !== undefined && amount !== null && amount !== ''
        && parseFloat(amount) !== calculatedAmount) {
        return res.status(400).json(ApiResponse.error('Invalid amount'));
    }

    /*
     * WHO IS PAYING, and it is not always a member.
     *
     * A guest booking has no profile to read — `optionalAuth` above leaves
     * `user` empty — so the booking's own `bookedBy` is the buyer. It is also
     * the better answer for a SIGNED-IN booker: they typed those details into
     * the booking form minutes ago, and a stale profile number would send the
     * gateway's receipt somewhere they are not reading.
     *
     * The profile is still the source for a membership, where there is no
     * form to read from and the account IS the buyer.
     */
    let buyerName = '';
    let buyerEmail = '';
    let buyerPhone = '';

    if (bookingContact) {
        buyerName = bookingContact.name || '';
        buyerEmail = bookingContact.email || '';
        buyerPhone = bookingContact.phone || '';
    }

    let profile = null;
    if (!buyerEmail || !buyerPhone) {
        const MemberDetails = require('../members/memberdetails.model');
        profile = await MemberDetails.findOne({
            $or: [
                ...(mongoose.Types.ObjectId.isValid(user.userId) ? [{ _id: user.userId }] : []),
                { email: String(user.email || '').toLowerCase() }
            ]
        }).catch(() => null);

        buyerName = buyerName || (profile && profile.fullName) || user.email || '';
        buyerEmail = buyerEmail || (profile && profile.email) || user.email || '';
        buyerPhone = buyerPhone || (profile && profile.phoneNumber) || '';
    }

    if (!buyerPhone) {
        return res.status(400).json(ApiResponse.error(
            orderType === 'event_booking'
                ? 'A mobile number is required to pay for this booking.'
                : 'A mobile number is required before paying. Please add one to your profile and try again.'
        ));
    }

    /*
     * THE ORDER ID IS MINTED BEFORE THE REQUEST, so it can travel in the
     * return URL.
     *
     * The member comes back from Instamojo on a fresh page load with nothing
     * of ours in memory, and the only identifiers in the URL are Instamojo's
     * own. Carrying our order id in `redirect_url` is what lets that page ask
     * "did THIS order get paid" instead of trusting `payment_status=Credit`
     * out of an address bar the member can edit.
     *
     * Instamojo APPENDS its query string to whatever `redirect_url` already
     * has, so a `?` here is kept and its parameters arrive alongside ours.
     */
    const orderId = 'ord_' + require('crypto').randomBytes(16).toString('hex');

    /*
     * BACK TO THE SITE THEY PAID FROM. The request's own Origin, when it is
     * one this API already trusts (CORS_ORIGIN), else FRONTEND_URL. Always
     * using FRONTEND_URL sent someone paying on a local or staging site to the
     * live one after Instamojo — a 404 whenever that site was down, and a
     * payment whose confirmation page they never saw.
     */
    const trusted = (require('../../config').cors.origin || []).map((o) => String(o).trim().replace(/\/+$/, ''));
    const origin = String(req.headers.origin || '').trim().replace(/\/+$/, '');
    const siteBase = (origin && trusted.includes(origin)) ? origin : String(process.env.FRONTEND_URL || '').replace(/\/+$/, '');

    const returnUrl = `${siteBase}/payment-success`
        + `?orderId=${encodeURIComponent(orderId)}`;

    const paymentData = {
        amount: calculatedAmount,
        purpose: finalPurpose,
        buyerName,
        email: buyerEmail,
        phone: buyerPhone,
        redirectUrl: returnUrl,
        webhookUrl: `${process.env.BACKEND_URL}/api/v1/webhook/instamojo`
    };

    const result = await paymentService.createPaymentRequest(paymentData);

    // Create the PaymentOrder to track the Instamojo payment request
    const PaymentOrder = require('./paymentorder.model');
    await PaymentOrder.create({
        orderId,
        memberId: profile ? profile._id : null,
        email: buyerEmail,
        planId: orderType === 'membership' ? planId : undefined,
        planName: orderType === 'membership' ? planId : undefined,
        amount: calculatedAmount,
        membershipType: orderType === 'membership' ? planId : undefined,
        orderType: orderType,
        /*
         * THE BOOKING'S OWN EVENT. It was taken from the request body, which the
         * website stopped sending — every order was saved with no event, so the
         * return page could never open the booking and sat on "still confirming",
         * and its View-my-booking button fell through to a page that is not there.
         */
        eventId: orderType === 'event_booking' ? bookingEventId : (eventId || undefined),
        bookingRef: bookingRef,
        provider: 'instamojo',
        gatewayPaymentId: result.payment_request_id, // Store the Instamojo request ID here
        expiresAt: new Date(Date.now() + 30 * 60 * 1000)
    });

    /*
     * `orderId` and `amount` ride back with the gateway's own fields.
     *
     * The caller is about to leave this site for Instamojo's checkout, so the
     * success page it returns to has nothing in memory. Handing it the order
     * id now is what lets that page ask "did my payment land" about a
     * SPECIFIC order rather than guessing from the query string Instamojo
     * puts in the URL — which the member's browser can edit.
     *
     * `amount` is the figure the SERVER charged, so a receipt cannot print
     * the number the plans screen happened to be showing.
     */
    res.status(201).json(ApiResponse.created({
        ...result,
        orderId,
        amount: calculatedAmount
    }, 'Payment request created'));
}));

/**
 * GET /api/v1/payment/return/:orderId?payment_id=&payment_status=
 *
 * What the `/payment-success` page asks when the buyer comes back from
 * Instamojo. PUBLIC — a guest who paid for seats has no token, and this page
 * calling the signed-in `/order/:id` sent every guest to the login screen
 * with their money gone. For an event booking it verifies the payment with
 * Instamojo itself and confirms the booking (see `resolveReturn`); for a
 * membership it only reports the order's state.
 */
const returnLimiter = require('../../core/middleware/rateLimit')
    .createRateLimiter({ windowMs: 10 * 60 * 1000, max: 200 });

router.get('/return/:orderId', returnLimiter, asyncHandler(async(req, res) => {
    const result = await paymentService.resolveReturn(req.params.orderId, {
        paymentId: String(req.query.payment_id || '').slice(0, 100),
        gatewayStatus: String(req.query.payment_status || '').slice(0, 30)
    });
    res.json(ApiResponse.success(result));
}));

/**
 * GET /api/v1/payment/status/:paymentRequestId
 * Check payment status
 * Requires authentication
 */
router.get('/status/:paymentRequestId', verifyToken, asyncHandler(async(req, res) => {
    const { paymentRequestId } = req.params;

    const result = await paymentService.checkPaymentStatus(paymentRequestId);

    res.json(ApiResponse.success(result));
}));

/**
 * POST /api/v1/payment/renew
 * Renew membership manually (admin use)
 * Requires authentication
 */
router.post('/renew', verifyToken, requireRole('super_admin'), asyncHandler(async(req, res) => {
    /*
     * Admin-only, and it was not.
     *
     * The comment above has always said "admin use", but the route was gated on
     * `verifyToken` alone: any signed-in member could rename someone else in the
     * `memberId` field and grant them a membership at an `amount` they chose —
     * including themselves. It is the same hole as the old `/complete`, reached
     * a different way.
     *
     * A member paying for their own renewal goes through `/payment/order` like
     * any other purchase. This route is only for an administrator recording a
     * payment taken outside the system.
     */
    const { memberId, amount } = req.body || {};

    const result = await paymentService.renewMembership(memberId, amount);

    logger.warn('Membership renewed manually by an admin', {
        memberId,
        amount,
        adminId: req.user && (req.user.userId || req.user.id)
    });

    res.json(ApiResponse.success(result, 'Membership renewed successfully'));
}));

/**
 * GET /api/v1/payment/plans
 * The plans and their prices, as the server holds them.
 * Public: a client needs them to render the picker, and they are not secret —
 * what matters is that the client cannot *change* them.
 */
router.get('/plans', asyncHandler(async(req, res) => {
    res.json(ApiResponse.success({
        plans: listPlans(),
        mockMode: orderService.isMockMode()
    }));
}));

/**
 * POST /api/v1/payment/order
 * Begin a payment. Body: { planId, applicationId? }
 *
 * The amount is NOT accepted from the caller — it is looked up from the plan.
 */
router.post('/order', verifyToken, asyncHandler(async(req, res) => {
    const { receipt } = await orderService.createOrder(req.user, {
        planId: req.body && req.body.planId,
        applicationId: req.body && req.body.applicationId
    });

    /*
     * Queued, not sent — and the difference is the whole point.
     *
     * The website completes a payment about a second after opening the order
     * (`payForMembership` runs order → authorise → complete in one click), so
     * firing PAYMENT_REQUIRED here delivered "your payment of ₹10,000 is still
     * pending" immediately followed by "your membership is now completely
     * active". `schedulePendingPaymentNotice` waits, re-reads the order, and
     * stays quiet when the payment has landed. See the note on
     * PENDING_NOTICE_DELAY_MS.
     */
    orderService.schedulePendingPaymentNotice(receipt.orderId);

    res.status(201).json(ApiResponse.created(receipt, 'Payment order created'));
}));

/**
 * GET /api/v1/payment/order/:orderId
 * The caller's own order. Another member's returns 403.
 */
router.get('/order/:orderId', verifyToken, asyncHandler(async(req, res) => {
    const order = await orderService.getOrder(req.user, req.params.orderId);
    res.json(ApiResponse.success(order));
}));

/**
 * POST /api/v1/payment/mock-authorize
 * Body: { orderId }
 *
 * Stands in for the gateway until a real one is connected: the server signs its
 * own order and hands back the three values a gateway would return. Refused
 * unless `PAYMENT_MODE=mock`, and never available in production.
 *
 * This is the single route that a real integration deletes.
 */
router.post('/mock-authorize', verifyToken, asyncHandler(async(req, res) => {
    const result = await orderService.authorizeMock(req.user, {
        orderId: req.body && req.body.orderId
    });
    res.json(ApiResponse.success(result, 'Mock payment authorised — no money was taken'));
}));

/**
 * POST /api/v1/payment/complete
 * Body: { orderId, gatewayPaymentId, signature, paymentMethod? }
 *
 * Verify a payment and activate the membership.
 *
 * This route used to accept `{ paymentId, paymentMethod, transactionId, status }`
 * and trust all of it. None of those fields was checked against anything —
 * there was nothing to check them against — so an authenticated request with an
 * **empty body** set `membershipStatus` to `approved`. Any member who could sign
 * in could grant themselves a paid membership without a card.
 *
 * It now requires a server-created order, refuses one that is not the caller's,
 * refuses one that has already been paid, and verifies an HMAC signature over
 * `orderId|gatewayPaymentId` before writing anything. The amount recorded comes
 * from the order rather than from the request.
 */
router.post('/complete', verifyToken, asyncHandler(async(req, res) => {
    const body = req.body || {};

    const { order, member } = await orderService.completePayment(req.user, {
        orderId: body.orderId,
        gatewayPaymentId: body.gatewayPaymentId,
        signature: body.signature,
        paymentMethod: body.paymentMethod
    });

    /*
     * Bell, email and WhatsApp — one call, and it cannot fail this request.
     *
     * The money has already moved and the membership is already active by the
     * time this line runs. `dispatchInBackground` never throws and is not
     * awaited, so neither an unreachable mail host nor a WhatsApp outage can
     * turn a completed payment into an error the member sees — which would send
     * them to pay a second time for a membership they already hold.
     *
     * The region comes off the member record so the receipt email is replyable
     * to their own regional office rather than to a no-reply address.
     */
    notificationService.dispatchInBackground('MEMBERSHIP_ACTIVATED', {
        id: member._id,
        name: member.fullName,
        email: member.email,
        phone: member.phoneNumber,
        whatsapp: member.whatsappNumber,
        state: member.state,
        district: member.district,
        block: member.block
    }, {
        /*
         * THE SAME EXPRESSION THE WEBSITE PRINTS, not the raw field.
         *
         * `membershipNumber` is not on the `MemberDetails` schema at all — it is
         * derived, and `member.controller.js` (twice) and
         * `memberExtras.controller.js` all derive it the same way. Reading the
         * bare field here is `undefined` on every member who has ever paid, so
         * the activation email arrived with an empty "Member ID" line beside a
         * dashboard showing one. Mongoose drops the unknown path without a word,
         * which is why nothing ever reported it.
         */
        membershipNumber: member.membershipNumber
            || String(member._id || '').slice(-8).toUpperCase(),
        membershipType: member.membershipType,
        /*
         * `order.amount` is in RUPEES — the order model says so explicitly, and
         * only the membership PLAN rows store paise. Reading `amountPaise` here
         * returns undefined and the receipt prints no amount at all, with
         * nothing reporting an error: the same silent-drop pattern the member
         * collections are full of. Both names are read so a future rename
         * cannot reintroduce it, and the paise branch only fires when the rupee
         * field is genuinely absent.
         */
        amountLabel: (() => {
            const rupees = order.amount !== undefined && order.amount !== null
                ? Number(order.amount)
                : Number(order.amountPaise || 0) / 100;
            return Number.isFinite(rupees) && rupees > 0
                ? `₹${rupees.toLocaleString('en-IN')}`
                : '';
        })(),
        orderId: order.orderId,
        data: { membershipType: member.membershipType, orderId: order.orderId }
    });

    res.json(ApiResponse.success(member, 'Payment verified and membership activated'));
}));


module.exports = router;